# This is a basic workflow to help you get started with Actions

name: Java Gradle SAST CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: cdefense/sast-scan
      options: -e "WORKSPACE=/__w/vulnerable-java-gradle/vulnerable-java-gradle/target"
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Build with Gradle
    - name: Build with Gradle
      run: gradle build
      
      # Run SAST scan
    - name: SAST Scan
      run: python3 /usr/local/src/scan --src /__w/vulnerable-java-gradle/vulnerable-java-gradle/target --type java --app_name vulnerable-java-gradle --api-key 75a81a24-adfc-4bfd-8b32-7562169a9759
